language: objective-c
osx_image: xcode10.2
before_install:
  - gem install cocoapods -v '1.5.0'
install:
  - ./install_swiftlint.sh
script:
  - gem install travis
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build test -workspace Example/Cheats.xcworkspace -scheme Cheats-Example -destination "platform=iOS Simulator,name=iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  - pod lib lint --allow-warnings
  - swift build # Check Swift Package Manager module compiles